js_path = r'C:\Users\Administrator\Desktop\橱柜工厂管理系统\src\backend\full_test_abnormal_v1.js'

def jline(l):
    return l + '\n'

lines = []
append = lines.append

# Header
append("// 橱柜工厂系统 - 异常边界测试 V1")
append("const { Pool } = require('pg');")
append("const pool = new Pool({ host: process.env.DB_HOST || 'localhost', port: parseInt(process.env.DB_PORT || '5432'), user: process.env.DB_USER || 'postgres', password: process.env.DB_PASSWORD || 'postgres', database: process.env.DB_NAME || 'cabinet_factory', max: 10 });")
append("const uuid = () => require('crypto').randomUUID();")
append("const ri = (a, b) => Math.floor(Math.random() * (b - a + 1)) + a;")
append("const rf = (a, b) => parseFloat((Math.random() * (b - a) + a).toFixed(2));")
append("const pick = a => a[ri(0, a.length - 1)];")
append("const ts = () => Date.now().toString();")
append("const db = { query: (t, p) => pool.query(t, p) };")

# clearAll
append(jline("async function clearAll() {"))
append(jline("    console.log('\\n========================================');"))
append(jline("    console.log('  橱柜工厂 - 异常边界测试 V1');"))
append(jline("    console.log('========================================');"))
append(jline("    console.log('\\n========== 1. 清空数据 ==========');"))
append(jline("    const client = await pool.connect();"))
append(jline("    try {"))
append(jline("        await client.query(\"SET session_replication_role = 'replica';\");"))
append(jline("        await client.query(\"TRUNCATE TABLE payment_in, receivable, attendance_record, installation_progress, installer_allocation, installation_task, logistics_track, logistics_record, package_item, package_record, door_panel_production, countertop_production, production_schedule, production_worker, production_stage, stock_in, stock_out, stock_inventory, order_tracking, order_bom, order_detail, order_master, material_bom, material, warehouse, supplier, customer, employee, department CASCADE;\");"))
append(jline("        await client.query(\"SET session_replication_role = 'origin';\");"))
append(jline("        console.log('OK: 清空完成 (TRUNCATE CASCADE)');"))
append(jline("    } finally { client.release(); }"))
append(jline("}"))

# createBasic
append(jline("async function createBasic() {"))
append(jline("    console.log('\\n========== 2. 基础数据：部门+员工 ==========');"))
append(jline("    const client = await pool.connect();"))
append(jline("    const deptIds = {};"))
append(jline("    const empIds = [];"))
append(jline("    try {"))
append(jline("        await client.query('BEGIN');"))
append(jline("        const depts = ["))
append(jline("            { n: '销售部A', c: 'DEPT-SA' },"))
append(jline("            { n: '设计部A', c: 'DEPT-DE' },"))
append(jline("            { n: '生产部A', c: 'DEPT-PR' },"))
append(jline("            { n: '仓储部A', c: 'DEPT-WH' },"))
append(jline("            { n: '物流部A', c: 'DEPT-LO' },"))
append(jline("            { n: '安装部A', c: 'DEPT-IN' },"))
append(jline("            { n: '财务部A', c: 'DEPT-FI' },"))
append(jline("            { n: '人事部A', c: 'DEPT-HR' },"))
append(jline("        ];"))
append(jline("        for (const d of depts) {"))
append(jline("            const id = uuid();"))
append(jline("            deptIds[d.c] = id;"))
append(jline("            await client.query('INSERT INTO department(id,dept_code,dept_name,dept_type,status,created_at) VALUES($1,$2,$3,$4,\\'active\\',NOW())', [id, d.c, d.n, d.c.split('-')[0]]);"))
append(jline("        }"))
append(jline("        const emps = ["))
append(jline("            { n: '张三', d: 'DEPT-SA' }, { n: '李四', d: 'DEPT-SA' },"))
append(jline("            { n: '王五', d: 'DEPT-DE' }, { n: '赵六', d: 'DEPT-DE' },"))
append(jline("            { n: '钱七', d: 'DEPT-PR' }, { n: '孙八', d: 'DEPT-PR' },"))
append(jline("            { n: '周九', d: 'DEPT-WH' }, { n: '吴十', d: 'DEPT-WH' },"))
append(jline("            { n: '郑一', d: 'DEPT-LO' }, { n: '王二', d: 'DEPT-IN' },"))
append(jline("            { n: '冯三', d: 'DEPT-FI' }, { n: '陈四', d: 'DEPT-HR' },"))
append(jline("        ];"))
append(jline("        for (const e of emps) {"))
append(jline("            const id = uuid();"))
append(jline("            empIds.push({ id, name: e.n, dept: e.d });"))
append(jline("            await client.query('INSERT INTO employee(id,employee_no,employee_name,dept_id,position,phone,status,hire_date,created_at) VALUES($1,$2,$3,$4,\\'员工\\',\\'13800000000\\',\\'active\\',DATE\\'2024-01-01\\',NOW())', [id, 'E' + ts().slice(-6) + ri(100, 999), e.n, deptIds[e.d]]);"))
append(jline("        }"))
append(jline("        await client.query('COMMIT');"))
append(jline("        console.log('OK: ' + depts.length + '部门, ' + emps.length + '员工');"))
append(jline("        return { deptIds, empIds };"))
append(jline("    } catch (err) { await client.query('ROLLBACK'); throw err; }"))
append(jline("    finally { client.release(); }"))
append(jline("}"))

# createCustomers
append(jline("async function createCustomers() {"))
append(jline("    console.log('\\n========== 3. 客户（正常+异常） ==========');"))
append(jline("    const client = await pool.connect();"))
append(jline("    const custIds = [];"))
append(jline("    try {"))
append(jline("        await client.query('BEGIN');"))
append(jline("        const custData = ["))
append(jline("            { n: '张先生', p: '13800138001', a: '广州市天河区珠江新城花城大道', t: 'normal' },"))
append(jline("            { n: '李女士', p: '13800138002', a: '深圳市南山区科技园南区', t: 'normal' },"))
append(jline("            { n: '王先生', p: '138001380000123456', a: '佛山市禅城区季华六路绿地中心', t: 'abnormal_phone_long' },"))
append(jline("            { n: '赵先生', p: '', a: '广州市天河区珠江新城花城大道123号某某小区A栋1501房很长很长的补充描述', t: 'abnormal_empty_phone' },"))
append(jline("            { n: '刘女士', p: '', a: '东莞市南城区鸿福路108号', t: 'abnormal_empty_phone2' },"))
append(jline("            { n: '陈退', p: '13800138006', a: '珠海市香洲区情侣中路', t: 'abnormal_special' },"))
append(jline("        ];"))
append(jline("        for (const cu of custData) {"))
append(jline("            const id = uuid();"))
append(jline("            custIds.push({ id, name: cu.n, type: cu.t });"))
append(jline("            try {"))
append(jline("                await client.query('INSERT INTO customer(id,customer_no,customer_name,phone,province,city,district,address,status,source,created_at) VALUES($1,$2,$3,$4,\\'广东省\\',\\'广州市\\',\\'天河区\\',$5,\\'following\\',\\'测试\\',NOW())', [id, 'C' + ts().slice(-6) + ri(100, 999), cu.n, cu.p || null, cu.a]);"))
append(jline("                console.log('OK: ' + cu.n + ' [' + cu.t + ']');"))
append(jline("            } catch (e2) { console.log('FAIL: ' + cu.n + ' [' + cu.t + '] - ' + e2.message.split('\\n')[0]); }"))
append(jline("        }"))
append(jline("        await client.query('COMMIT');"))
append(jline("        return custIds;"))
append(jline("    } catch (err) { await client.query('ROLLBACK'); throw err; }"))
append(jline("    finally { client.release(); }"))
append(jline("}"))

# createSuppliers
append(jline("async function createSuppliers() {"))
append(jline("    console.log('\\n========== 4. 供应商 ==========');"))
append(jline("    const client = await pool.connect();"))
append(jline("    const suppIds = [];"))
append(jline("    try {"))
append(jline("        await client.query('BEGIN');"))
append(jline("        const supps = ["))
append(jline("            { n: '深圳伟业五金', c: 'SUP-SZ001', ct: '李经理', p: '13800138111' },"))
append(jline("            { n: '广州华南板材', c: 'SUP-GZ001', ct: '张经理', p: '13800138222' },"))
append(jline("            { n: '佛山高明石英石', c: 'SUP-FS001', ct: '王经理', p: '13800138333' },"))
append(jline("        ];"))
append(jline("        for (const s of supps) {"))
append(jline("            const id = uuid();"))
append(jline("            suppIds.push({ id, name: s.n });"))
append(jline("            await client.query('INSERT INTO supplier(id,supplier_code,supplier_name,contact_person,phone,province,city,supply_category,status,created_at) VALUES($1,$2,$3,$4,$5,\\'广东省\\',\\'深圳市\\',\\'原材料\\',\\'active\\',NOW())', [id, s.c, s.n, s.ct, s.p]);"))
append(jline("            console.log('OK: ' + s.n);"))
append(jline("        }"))
append(jline("        await client.query('COMMIT');"))
append(jline("        return suppIds;"))
append(jline("    } catch (err) { await client.query('ROLLBACK'); throw err; }"))
append(jline("    finally { client.release(); }"))
append(jline("}"))

# createWarehouses
append(jline("async function createWarehouses() {"))
append(jline("    console.log('\\n========== 5. 仓库 ==========');"))
append(jline("    const client = await pool.connect();"))
append(jline("    const whIds = [];"))
append(jline("    try {"))
append(jline("        await client.query('BEGIN');"))
append(jline("        const whs = ["))
append(jline("            { n: '广州总仓', c: 'WH001T' },"))
append(jline("            { n: '佛山分仓', c: 'WH002T' },"))
append(jline("            { n: '深圳分仓', c: 'WH003T' },"))
append(jline("        ];"))
append(jline("        for (const w of whs) {"))
append(jline("            const id = uuid();"))
append(jline("            whIds.push({ id, name: w.n });"))
append(jline("            await client.query('INSERT INTO warehouse(id,warehouse_code,warehouse_name,warehouse_type,province,city,district,address,status,created_at) VALUES($1,$2,$3,\\'main\\',\\'广东省\\',\\'广州市\\',\\'白云区\\',\\'广州市白云区钟落潭\\',\\'active\\',NOW())', [id, w.c, w.n]);"))
append(jline("            console.log('OK: ' + w.n);"))
append(jline("        }"))
append(jline("        await client.query('COMMIT');"))
append(jline("        return whIds;"))
append(jline("    } catch (err) { await client.query('ROLLBACK'); throw err; }"))
append(jline("    finally { client.release(); }"))
append(jline("}"))

# createMaterials
append(jline("async function createMaterials(suppIds) {"))
append(jline("    console.log('\\n========== 6. 材料（正常+边界） ==========');"))
append(jline("    const client = await pool.connect();"))
append(jline("    const matIds = [];"))
append(jline("    try {"))
append(jline("        await client.query('BEGIN');"))
append(jline("        const mats = ["))
append(jline("            { n: '304不锈钢板1.5mm', c: 'MAT-SUS15-' + ts().slice(-4), sp: 0, cat: '不锈钢' },"))
append(jline("            { n: '304不锈钢板2.0mm', c: 'MAT-SUS20-' + ts().slice(-4), sp: 0, cat: '不锈钢' },"))
append(jline("            { n: '石英石台面板白色', c: 'MAT-QS01-' + ts().slice(-4), sp: 380, cat: '台面' },"))
append(jline("            { n: '防火门板标准18mm', c: 'MAT-FM01-' + ts().slice(-4), sp: 220, cat: '门板' },"))
append(jline("            { n: '抽屉导轨普通型', c: 'MAT-DG01-' + ts().slice(-4), sp: 15, cat: '五金' },"))
append(jline("            { n: '液压铰链带缓冲', c: 'MAT-HJ01-' + ts().slice(-4), sp: 8, cat: '五金' },"))
append(jline("            { n: 'ABS封边条白色', c: 'MAT-FB01-' + ts().slice(-4), sp: 3, cat: '辅料' },"))
append(jline("            { n: 'LED灯带暖白色', c: 'MAT-LED-' + ts().slice(-4), sp: 25, cat: '电器' },"))
append(jline("        ];"))
append(jline("        for (const m of mats) {"))
append(jline("            const id = uuid();"))
append(jline("            matIds.push({ id, name: m.n, code: m.c });"))
append(jline("            try {"))
append(jline("                await client.query('INSERT INTO material(id,material_code,material_name,category,specification,unit,unit_price,safe_stock,supplier_id,supplier_name,status,created_at) VALUES($1,$2,$3,$4,\\'标准\\',\\'张\\',$5,100,$6,\\'供应商\\',\\'active\\',NOW())', [id, m.c, m.n, m.cat, m.sp, suppIds[0] ? suppIds[0].id : null]);"))
append(jline("                console.log('OK: ' + m.n + ' [price=' + m.sp + ']');"))
append(jline("            } catch (me) { console.log('FAIL: ' + m.n + ' - ' + me.message.split('\\n')[0]); }"))
append(jline("        }"))
append(jline("        await client.query('COMMIT');"))
append(jline("        return matIds;"))
append(jline("    } catch (err) { await client.query('ROLLBACK'); throw err; }"))
append(jline("    finally { client.release(); }"))
append(jline("}"))

# createOrders
append(jline("async function createOrders(custIds) {"))
append(jline("    console.log('\\n========== 7. 订单（正常+边界） ==========');"))
append(jline("    const client = await pool.connect();"))
append(jline("    const orderIds = [];"))
append(jline("    try {"))
append(jline("        await client.query('BEGIN');"))
append(jline("        const orders = ["))
append(jline("            { cIdx: 0, amt: 34202.29, days: -30, late: false, prio: 3 },"))
append(jline("            { cIdx: 1, amt: 26960.58, days: -25, late: false, prio: 3 },"))
append(jline("            { cIdx: 2, amt: 22242.17, days: -20, late: false, prio: 3 },"))
append(jline("            { cIdx: 3, amt: 42915.07, days: -60, late: true, prio: 5 },"))
append(jline("            { cIdx: 4, amt: 15000.00, days: -90, late: true, prio: 5 },"))
append(jline("            { cIdx: 5, amt: 0, days: -15, late: false, prio: 3 },"))
append(jline("            { cIdx: 0, amt: 98765.43, days: -5, late: false, prio: 5 },"))
append(jline("        ];"))
append(jline("        for (const o of orders) {"))
append(jline("            const id = uuid();"))
append(jline("            const cust = custIds[o.cIdx] || custIds[0];"))
append(jline("            orderIds.push({ id, total: o.amt, late: o.late });"))
append(jline("            const delDate = new Date();"))
append(jline("            delDate.setDate(delDate.getDate() + 15);"))
append(jline("            await client.query('INSERT INTO order_master(id,order_no,source_type,customer_id,order_status,total_amount,deposit_amount,balance_amount,expected_delivery,installation_required,priority,delivery_province,delivery_city,delivery_district,delivery_address,delivery_contact,delivery_phone,remark,created_at) VALUES($1,$2,\\'customer\\',$3,\\'pending\\',$4,$5,$6,$7,true,$8,\\'广东省\\',\\'广州市\\',\\'天河区\\',\\'天河区某小区\\',\\'客户\\',\\'13800000001\\',\\'测试订单\\',NOW())', [id, 'O' + ts().slice(-8) + ri(1000, 9999), cust.id, o.amt, o.amt * 0.3, o.amt * 0.7, delDate.toISOString().split('T')[0], o.prio]);"))
append(jline("            const detId = uuid();"))
append(jline("            await client.query('INSERT INTO order_detail(id,order_id,product_name,product_type,cabinet_count,board_count,has_boards,material,color,length,width,height,unit_price,quantity,amount,created_at) VALUES($1,$2,\\'标准橱柜\\',\\'定制品\\',2,8,true,\\'304不锈钢\\',\\'银色\\',800,600,2000,1,1,$3,NOW())', [detId, id, o.amt]);"))
append(jline("            const trkId = uuid();"))
append(jline("            await client.query('INSERT INTO order_tracking(id,order_id,current_stage,stage_name,stage_status,operator_name,started_at,created_at) VALUES($1,$2,\\'design\\',\\'设计阶段\\',\\'in_progress\\',\\'王五\\',NOW(),NOW())', [trkId, id]);"))
append(jline("            const bomId = uuid();"))
append(jline("            await client.query('INSERT INTO order_bom(id,order_id,material_code,material_name,material_type,specification,unit,quantity,unit_price,total_price,remark,created_at) VALUES($1,$2,\\'MAT-SUS15\\',\\'不锈钢板\\',\\'原材料\\',\\'1.5mm\\',\\'张\\',10,380,3800,NULL,NOW())', [bomId, id]);"))
append(jline("            var statusStr = o.amt === 0 ? '零金额' : o.late ? '逾期未交付' : '正常';"))
append(jline("            console.log('OK: ' + id.substring(0, 8) + '... [¥' + o.amt.toFixed(2) + '] [' + statusStr + ']');"))
append(jline("        }"))
append(jline("        await client.query('COMMIT');"))
append(jline("        return orderIds;"))
append(jline("    } catch (err) { await client.query('ROLLBACK'); throw err; }"))
append(jline("    finally { client.release(); }"))
append(jline("}"))

# createStock
append(jline("async function createStock(matIds, whIds) {"))
append(jline("    console.log('\\n========== 8. 入库+库存（正常+边界） ==========');"))
append(jline("    const client = await pool.connect();"))
append(jline("    try {"))
append(jline("        await client.query('BEGIN');"))
append(jline("        // Zero stock: 铰链进10出10 -> 0"))
append(jline("        var zeroMat = matIds.find(m => m.name.indexOf('铰链') >= 0);"))
append(jline("        if (zeroMat) {"))
append(jline("            var inId = uuid();"))
append(jline("            await client.query('INSERT INTO stock_in(id,stock_in_no,warehouse_id,supplier_id,operator_name,total_amount,remark,created_at) VALUES($1,$2,$3,$4,\\'陈四\\',1200,\\'边界测试-零库存进10出10\\',NOW())', [inId, 'IN' + ts().slice(-6), whIds[0].id, null]);"))
append(jline("            var invId = uuid();"))
append(jline("            await client.query('INSERT INTO stock_inventory(id,warehouse_id,material_id,quantity,last_in_date,created_at,updated_at) VALUES($1,$2,$3,10,NOW(),NOW(),NOW()) ON CONFLICT (warehouse_id,material_id) DO UPDATE SET quantity=10,updated_at=NOW()', [invId, whIds[0].id, zeroMat.id]);"))
append(jline("            var outId = uuid();"))
append(jline("            await client.query('INSERT INTO stock_out(id,stock_out_no,warehouse_id,operator_name,total_amount,remark,created_at) VALUES($1,$2,$3,\\'周九\\',1200,\\'边界测试-零库存出库\\',NOW())', [outId, 'OUT' + ts().slice(-6), whIds[0].id]);"))
append(jline("            await client.query('UPDATE stock_inventory SET quantity=0,last_out_date=NOW(),updated_at=NOW() WHERE warehouse_id=$1 AND material_id=$2', [whIds[0].id, zeroMat.id]);"))
append(jline("            console.log('OK 边界库存: 铰链 -> 零库存（进10出10）');"))
append(jline("        }"))
append(jline("        // Low stock: < safe_stock"))
append(jline("        var lowMat = matIds.find(m => m.name.indexOf('1.5mm') >= 0);"))
append(jline("        if (lowMat) {"))
append(jline("            var inv2 = uuid();"))
append(jline("            await client.query('INSERT INTO stock_inventory(id,warehouse_id,material_id,quantity,last_in_date,created_at,updated_at) VALUES($1,$2,$3,5,NOW(),NOW(),NOW()) ON CONFLICT (warehouse_id,material_id) DO UPDATE SET quantity=5,updated_at=NOW()', [inv2, whIds[0].id, lowMat.id]);"))
append(jline("            console.log('OK 边界库存: 不锈钢板1.5mm -> 库存不足（5张，安全库存100）');"))
append(jline("        }"))
append(jline("        // Over stock: 99999 张"))
append(jline("        var overMat = matIds.find(m => m.name.indexOf('2.0mm') >= 0);"))
append(jline("        if (overMat) {"))
append(jline("            var inv3 = uuid();"))
append(jline("            await client.query('INSERT INTO stock_inventory(id,warehouse_id,material_id,quantity,last_in_date,created_at,updated_at) VALUES($1,$2,$3,99999,NOW(),NOW(),NOW()) ON CONFLICT (warehouse_id,material_id) DO UPDATE SET quantity=99999,updated_at=NOW()', [inv3, whIds[0].id, overMat.id]);"))
append(jline("            console.log('OK 边界库存: 不锈钢板2.0mm -> 超额入库99999张');"))
append(jline("        }"))
append(jline("        await client.query('COMMIT');"))
append(jline("    } catch (err) { await client.query('ROLLBACK'); throw err; }"))
append(jline("    finally { client.release(); }"))
append(jline("}"))

# createProduction
append(jline("async function createProduction(orders) {"))
append(jline("    console.log('\\n========== 9. 生产记录（正常+异常） ==========');"))
append(jline("    const client = await pool.connect();"))
append(jline("    try {"))
append(jline("        await client.query('BEGIN');"))
append(jline("        for (var pi = 0; pi < Math.min(4, orders.length); pi++) {"))
append(jline("            var order = orders[pi];"))
append(jline("            var doorId = uuid();"))
append(jline("            await client.query('INSERT INTO door_panel_production(id,order_id,door_no,door_type,length,width,thickness,weight,quantity,material,color,finish,has_handle,has_hinge,hinge_count,coating_type,coating_color,baking_temp,baking_time,status,cutting_complete,quality_complete,current_location,created_at) VALUES($1,$2,$3,\\'标准门板\\',800,600,18,25.5,2,\\'304不锈钢\\',\\'银色\\',\\'拉丝\\',true,\\'液压铰链\\',6,\\'粉末喷涂\\',\\'银色\\',180,30,\\'completed\\',CURRENT_TIMESTAMP-INTERVAL\\'3 days\\',CURRENT_TIMESTAMP,\\'仓库A区\\',NOW())', [doorId, order.id, 'D' + ts().slice(-6) + ri(100, 999)]);"))
append(jline("            var ctId = uuid();"))
append(jline("            await client.query('INSERT INTO countertop_production(id,order_id,production_no,countertop_type,material,length,width,thickness,color,edge_style,has_sink_hole,has_faucet_hole,quantity,status,cutting_complete,quality_complete,current_location,created_at) VALUES($1,$2,$3,\\'石英石台面\\',\\'石英石\\',2000,600,15,\\'白色\\',\\'磨边\\',true,true,1,\\'completed\\',CURRENT_TIMESTAMP-INTERVAL\\'2 days\\',CURRENT_TIMESTAMP,\\'仓库B区\\',NOW())', [ctId, order.id, 'CT' + ts().slice(-6) + ri(100, 999)]);"))
append(jline("            console.log('OK 生产: ' + order.id.substring(0, 8) + '... 门板+台面 [completed]');"))
append(jline("        }"))
append(jline("        // Late schedule: 2026-03-10, still pending"))
append(jline("        var lateOrder = orders.find(o => o.late);"))
append(jline("        if (lateOrder) {"))
append(jline("            var schId = uuid();"))
append(jline("            await client.query('INSERT INTO production_schedule(id,schedule_no,order_id,schedule_date,priority,status,stage,scheduled_date,estimated_hours,created_at) VALUES($1,$2,$3,DATE\\'2026-03-10\\',5,\\'scheduled\\',\\'cutting\\',DATE\\'2026-03-10\\',16,NOW())', [schId, 'SCH' + ts().slice(-6) + 'LATE', lateOrder.id]);"))
append(jline("            console.log('OK 边界生产: 延期排期（2026-03-10，至今未开始）');"))
append(jline("        }"))
append(jline("        // Quality rejected"))
append(jline("        if (orders[0]) {"))
append(jline("            var doorId2 = uuid();"))
append(jline