path = r'C:\Users\Administrator\Desktop\橱柜工厂管理系统\src\backend\full_test_abnormal_v1.js'
lines = []
def L(s): lines.append(s + '\n')

L("async function createOrders(custIds) {")
L("    console.log('\\n========== 7. 订单（正常+边界） ==========');")
L("    const client = await pool.connect(); const orderIds = [];")
L("    try {")
L("        await client.query('BEGIN');")
L("        const orders = [{ cIdx: 0, amt: 34202.29, late: false, prio: 3 }, { cIdx: 1, amt: 26960.58, late: false, prio: 3 }, { cIdx: 2, amt: 22242.17, late: false, prio: 3 }, { cIdx: 3, amt: 42915.07, late: true, prio: 5 }, { cIdx: 4, amt: 15000.00, late: true, prio: 5 }, { cIdx: 0, amt: 0, late: false, prio: 3 }, { cIdx: 1, amt: 98765.43, late: false, prio: 5 }];")
L("        for (const o of orders) {")
L("            const id = uuid(); const cust = custIds[o.cIdx] || custIds[0];")
L("            orderIds.push({ id, total: o.amt, late: o.late });")
L("            const delDate = new Date(); delDate.setDate(delDate.getDate() + 15);")
L("            await client.query('INSERT INTO order_master(id,order_no,source_type,customer_id,order_status,total_amount,deposit_amount,balance_amount,expected_delivery,installation_required,priority,delivery_province,delivery_city,delivery_district,delivery_address,delivery_contact,delivery_phone,remark,created_at) VALUES($1,$2,\\'customer\\',$3,\\'pending\\',$4,$5,$6,$7,true,$8,\\'广东省\\',\\'广州市\\',\\'天河区\\',\\'天河区某小区\\',\\'客户\\',\\'13800000001\\',\\'测试订单\\',NOW())', [id, 'O' + ts().slice(-8) + ri(1000,9999), cust.id, o.amt, o.amt * 0.3, o.amt * 0.7, delDate.toISOString().split('T')[0], o.prio]);")
L("            const detId = uuid();")
L("            await client.query('INSERT INTO order_detail(id,order_id,product_name,product_type,cabinet_count,board_count,has_boards,material,color,length,width,height,unit_price,quantity,amount,created_at) VALUES($1,$2,\\'标准橱柜\\',\\'定制品\\',2,8,true,\\'304不锈钢\\',\\'银色\\',800,600,2000,1,1,$3,NOW())', [detId, id, o.amt]);")
L("            const trkId = uuid();")
L("            await client.query('INSERT INTO order_tracking(id,order_id,current_stage,stage_name,stage_status,operator_name,started_at,created_at) VALUES($1,$2,\\'design\\',\\'设计阶段\\',\\'in_progress\\',\\'王五\\',NOW(),NOW())', [trkId, id]);")
L("            const bomId = uuid();")
L("            await client.query('INSERT INTO order_bom(id,order_id,material_code,material_name,material_type,specification,unit,quantity,unit_price,total_price,remark,created_at) VALUES($1,$2,\\'MAT-SUS15\\',\\'不锈钢板\\',\\'原材料\\',\\'1.5mm\\',\\'张\\',10,380,3800,NULL,NOW())', [bomId, id]);")
L("            var statusStr = o.amt === 0 ? '零金额' : o.late ? '逾期未交付' : '正常';")
L("            console.log('OK: ' + id.substring(0,8) + '... [¥' + o.amt.toFixed(2) + '] [' + statusStr + ']');")
L("        }")
L("        await client.query('COMMIT'); return orderIds;")
L("    } catch (err) { await client.query('ROLLBACK'); throw err; }")
L("    finally { client.release(); }")
L("}")

L("async function createStock(matIds, whIds) {")
L("    console.log('\\n========== 8. 入库+库存（正常+边界） ==========');")
L("    const client = await pool.connect();")
L("    try {")
L("        await client.query('BEGIN');")
L("        var zeroMat = matIds.find(m => m.name.indexOf('铰链') >= 0);")
L("        if (zeroMat) {")
L("            var inId = uuid();")
L("            await client.query('INSERT INTO stock_in(id,stock_in_no,warehouse_id,supplier_id,operator_name,total_amount,remark,created_at) VALUES($1,$2,$3,NULL,\\'陈四\\',1200,\\'边界-零库存进10出10\\',NOW())', [inId, 'IN' + ts().slice(-6), whIds[0].id]);")
L("            var invId = uuid();")
L("            await client.query('INSERT INTO stock_inventory(id,warehouse_id,material_id,quantity,last_in_date,created_at,updated_at) VALUES($1,$2,$3,10,NOW(),NOW(),NOW()) ON CONFLICT (warehouse_id,material_id) DO UPDATE SET quantity=10,updated_at=NOW()', [invId, whIds[0].id, zeroMat.id]);")
L("            var outId = uuid();")
L("            await client.query('INSERT INTO stock_out(id,stock_out_no,warehouse_id,operator_name,total_amount,remark,created_at) VALUES($1,$2,$3,\\'周九\\',1200,\\'边界-零库存出库\\',NOW())', [outId, 'OUT' + ts().slice(-6), whIds[0].id]);")
L("            await client.query('UPDATE stock_inventory SET quantity=0,last_out_date=NOW(),updated_at=NOW() WHERE warehouse_id=$1 AND material_id=$2', [whIds[0].id, zeroMat.id]);")
L("            console.log('OK 边界: 铰链 -> 零库存（进10出10）');")
L("        }")
L("        var lowMat = matIds.find(m => m.name.indexOf('1.5mm') >= 0);")
L("        if (lowMat) { var inv2 = uuid(); await client.query('INSERT INTO stock_inventory(id,warehouse_id,material_id,quantity,last_in_date,created_at,updated_at) VALUES($1,$2,$3,5,NOW(),NOW(),NOW()) ON CONFLICT (warehouse_id,material_id) DO UPDATE SET quantity=5,updated_at=NOW()', [inv2, whIds[0].id, lowMat.id]); console.log('OK 边界: 不锈钢板1.5mm -> 库存不足（5张，安全库存100）'); }")
L("        var overMat = matIds.find(m => m.name.indexOf('2.0mm') >= 0);")
L("        if (overMat) { var inv3 = uuid(); await client.query('INSERT INTO stock_inventory(id,warehouse_id,material_id,quantity,last_in_date,created_at,updated_at) VALUES($1,$2,$3,99999,NOW(),NOW(),NOW()) ON CONFLICT (warehouse_id,material_id) DO UPDATE SET quantity=99999,updated_at=NOW()', [inv3, whIds[0].id, overMat.id]); console.log('OK 边界: 不锈钢板2.0mm -> 超额入库99999张'); }")
L("        await client.query('COMMIT');")
L("    } catch (err) { await client.query('ROLLBACK'); throw err; }")
L("    finally { client.release(); }")
L("}")

L("async function createProduction(orders) {")
L("    console.log('\\n========== 9. 生产记录（正常+异常） ==========');")
L("    const client = await pool.connect();")
L("    try {")
L("        await client.query('BEGIN');")
L("        for (var pi = 0; pi < Math.min(4, orders.length); pi++) {")
L("            var order = orders[pi];")
L("            var doorId = uuid();")
L("            await client.query('INSERT INTO door_panel_production(id,order_id,door_no,door_type,length,width,thickness,weight,quantity,material,color,finish,has_handle,has_hinge,hinge_count,coating_type,coating_color,baking_temp,baking_time,status,cutting_complete,quality_complete,current_location,created_at) VALUES($1,$2,$3,\\'标准门板\\',800,600,18,25.5,2,\\'304不锈钢\\',\\'银色\\',\\'拉丝\\',true,\\'液压\\',6,\\'粉末喷涂\\',\\'银色\\',180,30,\\'completed\\',CURRENT_TIMESTAMP-INTERVAL\\'3 days\\',CURRENT_TIMESTAMP,\\'仓库A区\\',NOW())', [doorId, order.id, 'D' + ts().slice(-6) + ri(100,999)]);")
L("            var ctId = uuid();")
L("            await client.query('INSERT INTO countertop_production(id,order_id,production_no,countertop_type,material,length,width,thickness,color,edge_style,has_sink_hole,has_faucet_hole,quantity,status,cutting_complete,quality_complete,current_location,created_at) VALUES($1,$2,$3,\\'石英石台面\\',\\'石英石\\',2000,600,15,\\'白色\\',\\'磨边\\',true,true,1,\\'completed\\',CURRENT_TIMESTAMP-INTERVAL\\'2 days\\',CURRENT_TIMESTAMP,\\'仓库B区\\',NOW())', [ctId, order.id, 'CT' + ts().slice(-6) + ri(100,999)]);")
L("            console.log('OK 生产: ' + order.id.substring(0,8) + '... 门板+台面 [completed]');")
L("        }")
L("        var lateOrder = orders.find(o => o.late);")
L("        if (lateOrder) { var schId = uuid(); await client.query('INSERT INTO production_schedule(id,schedule_no,order_id,schedule_date,priority,status,stage,scheduled_date,estimated_hours,created_at) VALUES($1,$2,$3,DATE\\'2026-03-10\\',5,\\'scheduled\\',\\'cutting\\',DATE\\'2026-03-10\\',16,NOW())', [schId, 'SCH' + ts().slice(-6) + 'LATE', lateOrder.id]); console.log('OK 边界: 延期排期（2026-03-10，至今未开始）'); }")
L("        if (orders[0]) { var doorId2 = uuid(); await client.query('INSERT INTO door_panel_production(id,order_id,door_no,door_type,length,width,thickness,weight,quantity,material,color,finish,has_handle,has_hinge,hinge_count,coating_type,coating_color,baking_temp,baking_time,status,cutting_complete,quality_start,quality_complete,quality_result,quality_remark,current_location,created_at) VALUES($1,$2,$3,\\'标准门板\\',800,600,18,25.5,2,\\'304不锈钢\\',\\'银色\\',\\'拉丝\\',true,\\'液压\\',6,\\'粉末喷涂\\',\\'银色\\',180,30,\\'in_production\\',CURRENT_TIMESTAMP-INTERVAL\\'5 days\\',CURRENT_TIMESTAMP-INTERVAL\\'1 day\\',CURRENT_TIMESTAMP,\\'rejected\\',\\'涂层气泡超标，已返工2次\\',\\'待返工区\\',NOW())', [doorId2, orders[0].id, 'D' + ts().slice(-6) + 'BAD']); console.log('OK 边界: 门板质量不合格 [rejected]'); }")
L("        if (orders[1]) { var ctId2 = uuid(); await client.query('INSERT INTO countertop_production(id,order_id,production_no,countertop_type,material,length,width,thickness,color,edge_style,has_sink_hole,has_faucet_hole,quantity,status,cutting_complete,quality_start,quality_complete,quality_result,current_location,created_at) VALUES($1,$2,$3,\\'石英石台面\\',\\'石英石\\',2000,600,15,\\'白色\\',\\'磨边\\',true,true,1,\\'in_production\\',CURRENT_TIMESTAMP-INTERVAL\\'4 days\\',CURRENT_TIMESTAMP-INTERVAL\\'1 day\\',CURRENT_TIMESTAMP,\\'scrapped\\',\\'废料区\\',NOW())', [ctId2, orders[1].id, 'CT' + ts().slice(-6) + 'SCRP']); console.log('OK 边界: 台面报废 [scrapped]'); }")
L("        await client.query('COMMIT');")
L("    } catch (err) { await client.query('ROLLBACK'); throw err; }")
L("    finally { client.release(); }")
L("}")

L("async function createPackages(orders) {")
L("    console.log('\\n========== 10. 包装（正常+异常） ==========');")
L("    const client = await pool.connect();")
L("    try {")
L("        await client.query('BEGIN');")
L("        for (var pai = 0; pai < Math.min(3, orders.length); pai++) {")
L("            var order = orders[pai]; var pkgId = uuid();")
L("            var totalPkgs = ri(5, 15); var damagedPkgs = pai === 1 ? ri(1, 3) : 0; var missingPkgs = pai === 2 ? 2 : 0;")
L("            var remark = damagedPkgs > 0 ? '边界-部分破损' : missingPkgs > 0 ? '边界-缺件' : '正常包装';")
L("            await client.query('INSERT INTO package_record(id,package_no,order_id,package_type,package_method,total_packages,total_quantity,total_weight,status,scan_operator_name,storage_area,remark,created_at) VALUES($1,$2,$3,\\'纸箱+木架\\',\\'木架加固\\',$4,$5,$6,\\'stored\\',\\'周九\\',\\'仓库C区\\',$7,NOW())', [pkgId, 'PKG' + ts().slice(-6) + pai, order.id, totalPkgs, totalPkgs * ri(3,8), rf(50,200), remark]);")
L("            for (var paj = 0; paj < Math.min(3, totalPkgs); paj++) { var itemRemark = damagedPkgs > 0 && paj < damagedPkgs ? '轻微破损' : '正常'; await client.query('INSERT INTO package_item(id,package_id,product_name,product_type,quantity,weight,remark,created_at) VALUES($1,$2,$3,\\'橱柜\\',1,$4,$5,NOW())', [uuid(), pkgId, pick(['门板','台面','铰链','导轨','拉手']), rf(5,30), itemRemark]); }")
L("            var statusStr = damagedPkgs > 0 ? '部分破损' : missingPkgs > 0 ? '缺件' : '正常';")
L("            console.log('OK 包装: 订单' + (pai+1) + ' -> ' + totalPkgs + '件 [' + statusStr + ']');")
L("        }")
L("        if (orders.length > 3) { var pkgId2 = uuid(); await client.query('INSERT INTO package_record(id,package_no,order_id,package_type,package_method,total_packages,total_quantity,total_weight,status,scan_operator_name,storage_area,remark,created_at) VALUES($1,$2,$3,\\'纸箱\\',\\'标准\\',10,10,500,\\'stored\\',\\'周九\\',\\'仓库D区\\',\\'边界-明细数量不符\\',NOW())', [pkgId2, 'PKG' + ts().slice(-6) + 'X', orders[3].id]); await client.query('INSERT INTO package_item(id,package_id,product_name,quantity,weight,remark,created_at) VALUES($1,$2,\\'门板\\',1,25,\\'边界-明细只有1条\\',NOW())', [uuid(), pkgId2]); console.log('OK 边界: 记录10件但明细只有1条'); }")
L("        await client.query('COMMIT');")
L("    } catch (err) { await client.query('ROLLBACK'); throw err; }")
L("    finally { client.release(); }")
L("}")

L("async function createLogistics(orders) {")
L("    console.log('\\n========== 11. 物流（正常+异常） ==========');")
L("    const client = await pool.connect();")
L("    try {")
L("        await client.query('BEGIN');")
L("        var cities = ['深圳市南山区', '东莞市南城区', '佛山市禅城区', '惠州市惠城区'];")
L("        for (var li = 0; li < Math.min(4, orders.length); li++) {")
L("            var order = orders[li]; var logId = uuid(); var estDate = new Date(); estDate.setDate(estDate.getDate() + 3);")
L("            await client.query('INSERT INTO logistics_record(id,logistics_no,order_id,logistics_company,driver_name,driver_phone,freight,status,receive_province,receive_city,receive_district,receive_address,receive_contact,receive_phone,estimate_arrive,remark,created_at) VALUES($1,$2,$3,\\'顺丰速运\\',\\'司机张\\',\\'13800001111\\',500,\\'in_transit\\',\\'广东省\\',$4,$5,$6,$7,$8,\\'正常运输中\\',NOW())', [logId, 'LF' + ts().slice(-6) + li, order.id, cities[li].split('市')[0] + '市', cities[li] + '区', cities[li] + '具体地址', '客户', '13800000001', estDate.toISOString().split('T')[0]]);")
L("            console.log('OK 物流: -> ' + cities[li] + ' [in_transit]');")
L("        }")
L("        if (orders.length > 4) { var rejId = uuid(); await client.query('INSERT INTO logistics_record(id,logistics_no,order_id,logistics_company,driver_name,driver_phone,freight,status,receive_province,receive_city,receive_district,receive_address,receive_contact,receive_phone,remark,created_at) VALUES($1,$2,$3,\\'德邦物流\\',\\'司机李\\',\\'13800002222\\',800,\\'rejected\\',\\'广东省\\',\\'深圳市\\',\\'南山区\\',\\'客户地址\\',\\'客户\\',\\'13800000001\\',\\'边界-拒收(货物破损)\\',NOW())', [rejId, 'LF' + ts().slice(-6) + 'REJ', orders[4].id]); console.log('OK 边界物流: 拒收 [rejected]'); }")
L("        if (orders.length > 0) { var rtsId = uuid(); await client.query('INSERT INTO logistics_record(id,logistics_no,order_id,logistics_company,driver_name,driver_phone,freight,status,receive_province,receive_city,receive_district,receive_address,remark,created_at) VALUES($1,$2,$3,\\'中通速递\\',\\'司机王\\',\\'13800003333\\',300,\\'returned\\',\\'广东省\\',\\'佛山市\\',\\'禅城区\\',\\'客户地址\\',\\'边界-超时退回(10天未妥投)\\',NOW())', [rtsId, 'LF' + ts().slice(-6) + 'RTS', orders[0].id]); console.log('OK 边界物流: 超期退回 [returned]'); }")
L("        if (orders.length > 1) { var lateId = uuid(); var ovDate = new Date(); ovDate.setDate(ovDate.getDate() - 3); await client.query('INSERT INTO logistics_record(id,logistics_no,order_id,logistics_company,driver_name,driver_phone,freight,status,receive_province,receive_city,receive_district,receive_address,receive_contact,receive_phone,estimate_arrive,remark,created_at) VALUES($1,$2,$3,\\'韵达快递\\',\\'司机赵\\',\\'13800004444\\',300,\\'in_transit\\',\\'广东省\\',\\'广州市\\',\\'天河区\\',\\'客户地址\\',\\'客户\\',\\'13800000001\\',$4,\\'边界-已超期3天仍未到达\\',NOW())', [lateId, 'LF' + ts().slice(-6) + 'LATE', orders[1].id, ovDate.toISOString().split('T')[0]]); console.log('OK 边界物流: 超期未到达 [in_transit, 超期3天]'); }")
L("        await client.query('COMMIT');")
L("    } catch (err) { await client.query('ROLLBACK'); throw err; }")
L("    finally { client.release(); }")
L("}")

L("async function createInstallation(orders) {")
L("    console.log('\\n========== 12. 安装任务（正常+异常） ==========');")
L("    const client = await pool.connect();")
L("    try {")
L("        await client.query('BEGIN');")
L("        var instCities = ['深圳市南山区科苑花园', '东莞市南城区汇一城'];")
L("        for (var ii = 0; ii < Math.min(2, orders.length); ii++) {")
L("            var instId = uuid(); var appDate = new Date(); appDate.setDate(appDate.getDate() + 1);")
L("            await client.query('INSERT INTO installation_task(id,task_no,order_id,install_province,install_city,install_district,install_address,install_contact,install_phone,appointment_date,leader_name,status,accept_status,created_at) VALUES($1,$2,$3,\\'广东省\\',$4,$5,$6,$7,$8,$9,\\'王二\\',\\'in_progress\\',\\'pending\\',NOW())', [instId, 'IN' + ts().slice(-6) + ii, orders[ii].id, instCities[ii].split('市')[0] + '市', instCities[ii] + '区', instCities[ii] + '具体地址', '客户', '13800000001', appDate.toISOString().split('T')[0]]);")
L("            await client.query('INSERT INTO installer_allocation(id,task_id,employee_name,role,work_hours,allowance,created_at) VALUES($1,$2,\\'王二\\',\\'组长\\',8,0,NOW())', [uuid(), instId]);")
L("            await client.query('INSERT INTO installer_allocation(id,task_id,employee_name,role,work_hours,allowance,created_at) VALUES($1,$2,\\'郑一\\',\\'组员\\',8,0,NOW())', [uuid(), instId]);")
L("            await client.query('INSERT INTO installation_progress(id,task_id,progress,stage,stage_name,description,created_at) VALUES($1,$2,50,\\'installation\\',\\'安装中\\',\\'门板安装中\\',NOW())', [uuid(), instId]);")
L("            console.log('OK 安装: -> ' + instCities[ii] + ' [in_progress]');")
L("        }")
L("        if (orders.length > 2) { var failId = uuid(); await client.query('INSERT INTO installation_task(id,task_no,order_id,install_province,install_city,install_district,install_address,install_contact,install_phone,leader_name,status,accept_status,created_at) VALUES($1,$2,$3,\\'广东省\\',\\'佛山市\\',\\'禅城区\\',\\'禅城区某小区\\',\\'客户\\',\\'13800000001\\',\\'王二\\',\\'rework\\',\\'failed\\',NOW())', [failId, 'IN' + ts().slice(-6) + 'FW', orders[2].id]); await client.query('INSERT INTO installation_progress(id,task_id,progress,stage,stage_name,description,created_at) VALUES($1,$2,30,\\'dismantle\\',\\'拆旧\\',\\'已完成拆旧\\',NOW())', [uuid(), failId]); await client.query('INSERT INTO installation_progress(id,task_id,progress,stage,stage_name,description,created_at) VALUES($1,$2,60,\\'installation\\',\\'安装\\',\\'门板划伤，停工\\',NOW())', [uuid(), failId]); await client.query('INSERT INTO installation_progress(id,task_id,progress,stage,stage_name,description,created_at) VALUES($1,$2,0,\\'countertop\\',\\'台面\\',\\'等待返工\\',NOW())', [uuid(), failId]); console.log('OK 边界安装: 安装失败需返工 [rework]'); }")
L("        if (orders.length > 3) { var cmpId = uuid(); await client.query('INSERT INTO installation_task(id,task_no,order_id,install_province,install_city,install_district,install_address,install_contact,install_phone,leader_name,status,accept_status,accept_remark,visit_status,visit_remark,created_at) VALUES($1,$2,$3,\\'广东省\\',\\'惠州市\\',\\'惠城区\\',\\'惠城区某小区\\',\\'客户\\',\\'13800000001\\',\\'王二\\',\\'completed\\',\\'accepted\\',\\'勉强通过，缝隙超标\\',\\'visited\\',\\'客户很不满意\\',NOW())', [cmpId, 'IN' + ts().slice(-6) + 'CM', orders[3].id]); console.log('OK 边界安装: 完成但客户差评 [completed, visit_status=visited]'); }")
L("        await client.query('COMMIT');")
L("    } catch (err) { await client.query('ROLLBACK'); throw err; }")
L("    finally { client.release(); }")
L("}")

L("async function createAttendance(empIds) {")
L("    console.log('\\n========== 13. 考勤（正常+异常） ==========');")
L("    const client = await pool.connect();")
L("    try {")
L("        await client.query('BEGIN');")
L("        for (var ai = 0; ai < empIds.length; ai++) {")
L("            var emp = empIds[ai];")
L("            for (var ad = 0; ad < 20; ad++) { var d = new Date(); d.setDate(d.getDate() - ad); var dateStr = d.toISOString().split('T')[0]; await client.query('INSERT INTO attendance_record(id,employee_id,record_date,status,check_in_time,check_out_time,working_hours,remark,created_at) VALUES($1,$2,$3,\\'normal\\',$4,$5,8,\\'正常\\',NOW())', [uuid(), emp.id, dateStr, '08:0' + String(ad % 10), '18:0' + String(ad % 10)]); }")
L("            for (var aa = 21; aa <= 23; aa++) { var da = new Date(); da.setDate(da.getDate() - aa); await client.query('INSERT INTO attendance_record(id,employee_id,record_date,status,working_hours,remark,created_at) VALUES($1,$2,$3,\\'absent\\',0,\\'边界-旷工\\',NOW())', [uuid(), emp.id, da.toISOString().split('T')[0]]); }")
L("            var otDate = new Date(); otDate.setDate(otDate.getDate() - 24);")
L("            await client.query('INSERT INTO attendance_record(id,employee_id,record_date,status,check_in_time,check_out_time,working_hours,remark,created_at) VALUES($1,$2,$3,\\'normal\\',\\'08:00\\',\\'22:30\\',14,\\'边界-日加班6小时\\',NOW())', [uuid(), emp.id, otDate.toISOString().split('T')[0]]);")
L("            for (var al = 25; al <= 29; al++) { var dl = new Date(); dl.setDate(dl.getDate() - al); await client.query('INSERT INTO attendance_record(id,employee_id,record_date,status,check_in_time,check_out_time,working_hours,remark,created_at) VALUES($1,$2,$3,\\'late\\',\\'09:30\\',\\'18:00\\',7,\\'边界-迟到\\',NOW())', [uuid(), emp.id, dl.toISOString().split('T')[0]]); }")
L("        }")
L("        console.log('OK 考勤: ' + empIds.length + '人 x 30天（含旷工/加班/迟到异常）');")
L("        await client.query('COMMIT');")
L("    } catch (err) { await client.query('ROLLBACK'); throw err; }")
L("    finally { client.release(); }")
L("}")

L("async function createFinance(orders) {")
L("    console.log('\\n========== 14. 财务（正常+异常） ==========');")
L("    const client = await pool.connect();")
L("    try {")
L("        await client.query('BEGIN');")
L("        for (var fi = 0; fi < Math.min(3, orders.length); fi++) { var order = orders[fi]; var payId = uuid(); var amount = order.total > 0 ? order.total * 0.3 : rf(1000, 5000); await client.query('INSERT INTO payment_in(id,payment_no,source_type,amount,customer_id,customer_name,payment_method,status,order_id,remark,created_at) VALUES($1,$2,\\'order\\',$3,\\'00000000-0000-0000-0000-000000000000\\',\\'客户\\',\\'bank_transfer\\',\\'confirmed\\',$4,\\'正常收款\\',NOW())', [payId, 'PAY' + ts().slice(-8), amount, order.id]); console.log('OK 收款: ¥' + amount.toFixed(2) + ' [confirmed]'); }")
L("        var overId = uuid(); var overOrder = orders.find(o => o.total > 0) || orders[0];")
L("        if (overOrder) { await client.query(\"INSERT INTO receivable(id,dealer_id,order_id,bill_no,bill_date,due_date,amount,paid_amount,status,remark,created_at) VALUES($1,$2,$3,'BILL'+NOW()::text,DATE'2026-03-01',DATE'2026-03-15',$4,0,'overdue','边界-逾期20天',NOW())\", [overId, '00000000-0000-0000-0000-000000000000', overOrder.id, rf(10000, 30000)]); console.log('OK 边界财务: 逾期应收账款 [overdue, 逾期20天]'); }")
L("        var badId = uuid(); var badOrder = orders.find(o => o.total > 0);")
L("        if (badOrder) { await client.query(\"INSERT INTO receivable(id,dealer_id,order_id,bill_no,bill_date,due_date,amount,paid_amount,status,remark,created_at) VALUES($1,$2,$3,'BILL'+NOW()::text,DATE'2026-01-01',DATE'2026-01-15',$4,0,'bad_debt','边界-坏账(客户破产)',NOW())\", [badId, '00000000-0000-0000-0000-000000000000', badOrder.id, rf(20000, 50000)]); console.log('OK 边界财务: 坏账 [bad_debt]'); }")
L("        if (orders.length > 1 && orders[1].total > 0) { var refId = uuid(); await client.query('INSERT INTO payment_in(id,payment_no,source_type,amount,customer_id,customer_name,payment_method,status,order_id,remark,created_at) VALUES($1,$2,\\'order\\',-$3,\\'00000000-0000-0000-0000-000000000000\\',\\'客户\\',\\'bank_transfer\\',\\'refunded\\',$4,\\'边界-部分退款(产品质量问题)\\',NOW())', [refId, 'PAY' + ts().slice(-8), orders[1].total * 0.2, orders[1].id]); console.log('OK 边界财务: 部分退款 ¥' + (orders[1].total * 0.2).toFixed(2)); }")
L("        await client.query('COMMIT');")
L("    } catch (err) { await client.query('ROLLBACK'); throw err; }")
L("    finally { client.release(); }")
L("}")

L("async function verifyReports() {")
L("    console.log('\\n========== 15. 报表验证 ==========');")
L("    try {")
L("        var att = await db.query(\"SELECT e.employee_name, COUNT(*) FILTER (WHERE a.status='normal') as normal_days, COUNT(*) FILTER (WHERE a.status='absent') as absent_days, COUNT(*) FILTER (WHERE a.status='late') as late_days FROM attendance_record a JOIN employee e ON e.id=a.employee_id GROUP BY e.employee_name ORDER BY e.employee_name\");")
L("        console.log('\\n[考勤异常统计]'); console.table(att.rows);")
L("        var inv = await db.query(\"SELECT m.material_name, w.warehouse_name, i.quantity FROM stock_inventory i JOIN material m ON m.id=i.material_id JOIN warehouse w ON w.id=i.warehouse_id ORDER BY i.quantity ASC NULLS LAST\");")
L("        console.log('\\n[库存（按数量升序）]'); console.table(inv.rows);")
L("        var rec = await db.query(\"SELECT order_id, amount, paid_amount, status, remark FROM receivable WHERE status IN ('overdue','bad_debt')\");")
L("        console.log('\\n[逾期/坏账应收款]'); console.table(rec.rows);")
L("        var log = await db.query(\"SELECT logistics_no, logistics_company, status, remark FROM logistics_record ORDER BY created_at DESC\");")
L("        console.log('\\n[物流状态]'); console.table(log.rows);")
L("        var inst = await db.query(\"SELECT task_no, status, accept_status, visit_status FROM installation_task ORDER BY created_at DESC\");")
L("        console.log('\\n[安装任务]'); console.table(inst.rows);")
L("        var pkg = await db.query(\"SELECT pr.package_no, pr.total_packages, (SELECT COUNT(*) FROM package_item pi WHERE pi.package_id=pr.id) as item_count, pr.remark FROM package_record pr ORDER BY pr.created_at DESC\");")
L