path = r'C:\Users\Administrator\Desktop\橱柜工厂管理系统\src\backend\full_test_abnormal_v1.js'

lines = []

lines.append("")
lines.append("async function createStock(matIds, whIds) {")
lines.append("    console.log('\\n========== 8. 入库+库存（正常+边界） ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        // Zero stock")
lines.append("        var zeroMat = null;")
lines.append("        for (var mi = 0; mi < matIds.length; mi++) { if (matIds[mi].name.indexOf('铰链') >= 0) { zeroMat = matIds[mi]; break; } }")
lines.append("        if (zeroMat) {")
lines.append("            var inId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO stock_in (id,warehouse_id,material_id,quantity,unit_price,total_amount,operator,source,status,remark,created_at) VALUES ($1,$2,$3,10,12,120,\\'陈四\\',\\'采购入库\\',\\'checked\\',\\'边界测试-零库存\\',NOW())',")
lines.append("                [inId, whIds[0].id, zeroMat.id]")
lines.append("            );")
lines.append("            await client.query(")
lines.append("                'INSERT INTO stock_inventory (id,warehouse_id,material_id,quantity,unit_price,total_value,last_in_id,last_out_id,created_at,updated_at) VALUES ($1,$2,$3,10,12,120,$4,NULL,NOW(),NOW()) ON CONFLICT (warehouse_id,material_id) DO UPDATE SET quantity=10,total_value=120,updated_at=NOW()',")
lines.append("                [uuid(), whIds[0].id, zeroMat.id, inId]")
lines.append("            );")
lines.append("            var outId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO stock_out (id,warehouse_id,material_id,quantity,unit_price,total_amount,operator,purpose,status,remark,created_at) VALUES ($1,$2,$3,10,12,120,\\'周九\\',\\'生产领用\\',\\'approved\\',\\'边界测试-零库存出库\\',NOW())',")
lines.append("                [outId, whIds[0].id, zeroMat.id]")
lines.append("            );")
lines.append("            await client.query(")
lines.append("                'UPDATE stock_inventory SET quantity=0,total_value=0,last_out_id=$4,updated_at=NOW() WHERE warehouse_id=$2 AND material_id=$3',")
lines.append("                [null, whIds[0].id, zeroMat.id, outId]")
lines.append("            );")
lines.append("            console.log('OK 边界库存: 铰链 -> 零库存（进10出10）');")
lines.append("        }")
lines.append("        // Low stock (only 5)")
lines.append("        var lowMat = null;")
lines.append("        for (var mi2 = 0; mi2 < matIds.length; mi2++) { if (matIds[mi2].name.indexOf('1.5mm') >= 0) { lowMat = matIds[mi2]; break; } }")
lines.append("        if (lowMat) {")
lines.append("            var inId2 = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO stock_in (id,warehouse_id,material_id,quantity,unit_price,total_amount,operator,source,status,remark,created_at) VALUES ($1,$2,$3,5,380,1900,\\'陈四\\',\\'采购入库\\',\\'checked\\',\\'边界测试-库存不足\\',NOW())',")
lines.append("                [inId2, whIds[0].id, lowMat.id]")
lines.append("            );")
lines.append("            await client.query(")
lines.append("                'INSERT INTO stock_inventory (id,warehouse_id,material_id,quantity,unit_price,total_value,last_in_id,last_out_id,created_at,updated_at) VALUES ($1,$2,$3,5,380,1900,$4,NULL,NOW(),NOW()) ON CONFLICT (warehouse_id,material_id) DO UPDATE SET quantity=5,total_value=1900,updated_at=NOW()',")
lines.append("                [uuid(), whIds[0].id, lowMat.id, inId2]")
lines.append("            );")
lines.append("            console.log('OK 边界库存: 不锈钢板 -> 库存不足（5个）');")
lines.append("        }")
lines.append("        // Over stock (99999)")
lines.append("        var overMat = null;")
lines.append("        for (var mi3 = 0; mi3 < matIds.length; mi3++) { if (matIds[mi3].name.indexOf('2.0mm') >= 0) { overMat = matIds[mi3]; break; } }")
lines.append("        if (overMat) {")
lines.append("            var inId3 = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO stock_in (id,warehouse_id,material_id,quantity,unit_price,total_amount,operator,source,status,remark,created_at) VALUES ($1,$2,$3,99999,520,51999480,\\'陈四\\',\\'大批量采购\\',\\'checked\\',\\'边界测试-超额入库99999张\\',NOW())',")
lines.append("                [inId3, whIds[0].id, overMat.id]")
lines.append("            );")
lines.append("            await client.query(")
lines.append("                'INSERT INTO stock_inventory (id,warehouse_id,material_id,quantity,unit_price,total_value,last_in_id,last_out_id,created_at,updated_at) VALUES ($1,$2,$3,99999,520,51999480,$4,NULL,NOW(),NOW()) ON CONFLICT (warehouse_id,material_id) DO UPDATE SET quantity=99999,total_value=51999480,updated_at=NOW()',")
lines.append("                [uuid(), whIds[0].id, overMat.id, inId3]")
lines.append("            );")
lines.append("            console.log('OK 边界库存: 2.0mm板 -> 超额入库99999张');")
lines.append("        }")
lines.append("        await client.query('COMMIT');")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createProduction(orders) {")
lines.append("    console.log('\\n========== 9. 生产记录（正常+异常） ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        for (var pi = 0; pi < Math.min(4, orders.length); pi++) {")
lines.append("            var order = orders[pi];")
lines.append("            var doorId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO door_panel_production (id,order_id,door_no,door_type,length,width,thickness,weight,quantity,material,color,finish,has_handle,has_hinge,hinge_count,coating_type,coating_color,baking_temp,baking_time,status,cutting_complete,quality_complete,current_location,created_at) VALUES ($1,$2,$3,\\'标准门板\\',800,600,18,25.5,2,\\'304不锈钢\\',\\'银色\\',\\'拉丝\\',true,true,6,\\'粉末喷涂\\',\\'银色\\',180,30,\\'completed\\',CURRENT_TIMESTAMP-INTERVAL\\'3 days\\',CURRENT_TIMESTAMP,\\'仓库A区\\',NOW())',")
lines.append("                [doorId, order.id, 'D' + ts().slice(-6) + String(ri(100,999))]")
lines.append("            );")
lines.append("            var ctId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO countertop_production (id,order_id,production_no,countertop_type,material,length,width,thickness,color,edge_style,has_sink_hole,has_faucet_hole,quantity,status,cutting_complete,quality_complete,current_location,created_at) VALUES ($1,$2,$3,\\'石英石台面\\',\\'石英石\\',2000,600,15,\\'白色\\',\\'磨边\\',true,true,1,\\'completed\\',CURRENT_TIMESTAMP-INTERVAL\\'2 days\\',CURRENT_TIMESTAMP,\\'仓库B区\\',NOW())',")
lines.append("                [ctId, order.id, 'CT' + ts().slice(-6) + String(ri(100,999))]")
lines.append("            );")
lines.append("            console.log('OK 生产: ' + order.id.substring(0,8) + '... 门板+台面 完成');")
lines.append("        }")
lines.append("        // Late schedule")
lines.append("        var lateOrder = null;")
lines.append("        for (var li = 0; li < orders.length; li++) { if (orders[li].late) { lateOrder = orders[li]; break; } }")
lines.append("        if (lateOrder) {")
lines.append("            var schId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO production_schedule (id,schedule_no,order_id,schedule_date,priority,status,stage,scheduled_date,estimated_hours,created_at) VALUES ($1,$2,$3,DATE\\'2026-03-10\\',5,\\'scheduled\\',\\'cutting\\',DATE\\'2026-03-10\\',16,NOW())',")
lines.append("                [schId, 'SCH' + ts().slice(-6) + 'LATE', lateOrder.id]")
lines.append("            );")
lines.append("            console.log('OK 边界生产: 延期排期（2026-03-10，至今未开始）');")
lines.append("        }")
lines.append("        // Quality rejected")
lines.append("        if (orders[0]) {")
lines.append("            var doorId2 = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO door_panel_production (id,order_id,door_no,door_type,length,width,thickness,weight,quantity,material,color,finish,has_handle,has_hinge,hinge_count,coating_type,coating_color,baking_temp,baking_time,status,cutting_complete,quality_start,quality_complete,quality_result,quality_remark,current_location,created_at) VALUES ($1,$2,$3,\\'标准门板\\',800,600,18,25.5,2,\\'304不锈钢\\',\\'银色\\',\\'拉丝\\',true,true,6,\\'粉末喷涂\\',\\'银色\\',180,30,\\'in_production\\',CURRENT_TIMESTAMP-INTERVAL\\'5 days\\',CURRENT_TIMESTAMP-INTERVAL\\'1 day\\',CURRENT_TIMESTAMP,\\'rejected\\',\\'涂层气泡超标，已返工2次\\',\\'待返工区\\',NOW())',")
lines.append("                [doorId2, orders[0].id, 'D' + ts().slice(-6) + 'BAD']")
lines.append("            );")
lines.append("            console.log('OK 边界生产: 门板质量不合格（rejected, 返工2次）');")
lines.append("        }")
lines.append("        // Scrapped")
lines.append("        if (orders[1]) {")
lines.append("            var ctId2 = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO countertop_production (id,order_id,production_no,countertop_type,material,length,width,thickness,color,edge_style,has_sink_hole,has_faucet_hole,quantity,status,cutting_complete,quality_start,quality_complete,quality_result,current_location,created_at) VALUES ($1,$2,$3,\\'石英石台面\\',\\'石英石\\',2000,600,15,\\'白色\\',\\'磨边\\',true,true,1,\\'in_production\\',CURRENT_TIMESTAMP-INTERVAL\\'4 days\\',CURRENT_TIMESTAMP-INTERVAL\\'1 day\\',CURRENT_TIMESTAMP,\\'scrapped\\',\\'开裂严重无法修复，直接报废\\',\\'废料区\\',NOW())',")
lines.append("                [ctId2, orders[1].id, 'CT' + ts().slice(-6) + 'SCRP']")
lines.append("            );")
lines.append("            console.log('OK 边界生产: 台面报废（scrapped）');")
lines.append("        }")
lines.append("        await client.query('COMMIT');")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createPackages(orders) {")
lines.append("    console.log('\\n========== 10. 包装（正常+异常） ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        for (var pai = 0; pai < Math.min(3, orders.length); pai++) {")
lines.append("            var order = orders[pai];")
lines.append("            var pkgId = uuid();")
lines.append("            var totalPkgs = ri(5, 15);")
lines.append("            var damagedPkgs = pai === 1 ? ri(1, 3) : 0;")
lines.append("            var missingPkgs = pai === 2 ? 2 : 0;")
lines.append("            var remark = damagedPkgs > 0 ? '边界测试-部分破损' : missingPkgs > 0 ? '边界测试-缺件' : '正常包装';")
lines.append("            await client.query(")
lines.append("                'INSERT INTO package_record (id,order_id,package_no,total_packages,damaged_packages,missing_packages,package_type,package_weight,package_volume,storage_location,storage_date,status,operator,remark,created_at) VALUES ($1,$2,$3,$4,$5,$6,\\'纸箱+木架\\',$7,0.5,\\'仓库C区\\',CURRENT_DATE,\\'stored\\',\\'周九\\',$8,NOW())',")
lines.append("                [pkgId, order.id, 'PKG' + ts().slice(-6) + String(pai), totalPkgs, damagedPkgs, missingPkgs, rf(50, 200), remark]")
lines.append("            );")
lines.append("            for (var paj = 0; paj < Math.min(3, totalPkgs); paj++) {")
lines.append("                var itemRemark = damagedPkgs > 0 && paj < damagedPkgs ? '轻微破损' : '正常';")
lines.append("                await client.query(")
lines.append("                    'INSERT INTO package_item (id,package_id,item_name,quantity,weight,remark,created_at) VALUES ($1,$2,$3,1,$4,$5,NOW())',")
lines.append("                    [uuid(), pkgId, pick(['门板', '台面', '铰链', '导轨', '拉手']), rf(5, 30), itemRemark]")
lines.append("                );")
lines.append("            }")
lines.append("            var statusStr = damagedPkgs > 0 ? '部分破损' : missingPkgs > 0 ? '缺件' : '正常';")
lines.append("            console.log('OK 包装: 订单' + (pai+1) + ' -> ' + totalPkgs + '件 [' + statusStr + ']');")
lines.append("        }")
lines.append("        if (orders.length > 3) {")
lines.append("            var pkgId2 = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO package_record (id,order_id,package_no,total_packages,damaged_packages,missing_packages,package_type,package_weight,storage_location,storage_date,status,operator,remark,created_at) VALUES ($1,$2,$3,10,0,0,\\'纸箱\\',500,\\'仓库D区\\',CURRENT_DATE,\\'stored\\',\\'周九\\',\\'边界测试-明细数量不符\\',NOW())',")
lines.append("                [pkgId2, orders[3].id, 'PKG' + ts().slice(-6) + 'X']")
lines.append("            );")
lines.append("            await client.query(")
lines.append("                'INSERT INTO package_item (id,package_id,item_name,quantity,weight,remark,created_at) VALUES ($1,$2,\\'门板\\',1,25,\\'边界测试-明细只有1条\\',NOW())',")
lines.append("                [uuid(), pkgId2]")
lines.append("            );")
lines.append("            console.log('OK 边界包装: 记录10件但明细只有1条');")
lines.append("        }")
lines.append("        await client.query('COMMIT');")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createLogistics(orders) {")
lines.append("    console.log('\\n========== 11. 物流/运输（正常+异常） ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        var cities = ['深圳市', '东莞市', '佛山市', '惠州市', '中山市'];")
lines.append("        for (var li2 = 0; li2 < Math.min(4, orders.length); li2++) {")
lines.append("            var order = orders[li2];")
lines.append("            var logId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO logistics_record (id,order_id,logistics_no,carrier,driver_name,driver_phone,vehicle_no,shipping_address,estimated_arrival,actual_arrival,shipping_date,status,freight,remark,created_at) VALUES ($1,$2,$3,\\'顺丰速运\\',\\'司机\\',\\'13800001111\\',\\'粤B12345\\',$4,CURRENT_DATE+3,NULL,CURRENT_TIMESTAMP,\\'in_transit\\',500,\\'正常运输中\\',NOW())',")
lines.append("                [logId, order.id, 'LF' + ts().slice(-6) + String(li2), cities[li2] + '区']")
lines.append("            );")
lines.append("            console.log('OK 物流: -> ' + cities[li2] + ' [运输中]');")
lines.append("        }")
lines.append("        if (orders.length > 4) {")
lines.append("            var rejId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO logistics_record (id,order_id,logistics_no,carrier,driver_name,driver_phone,vehicle_no,shipping_address,estimated_arrival,actual_arrival,shipping_date,status,freight,rejection_reason,remark,created_at) VALUES ($1,$2,$3,\\'德邦物流\\',\\'司机\\',\\'13800002222\\',\\'粤B99999\\',\\'深圳市南山区\\',CURRENT_DATE+2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP-INTERVAL\\'2 days\\',\\'rejected\\',800,\\'客户拒收-货物破损\\',\\'边界测试-拒收\\',NOW())',")
lines.append("                [rejId, orders[4].id, 'LF' + ts().slice(-6) + 'REJ']")
lines.append("            );")
lines.append("            console.log('OK 边界物流: 拒收（货物破损）');")
lines.append("        }")
lines.append("        if (orders.length > 0) {")
lines.append("            var rtsId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO logistics_record (id,order_id,logistics_no,carrier,driver_name,driver_phone,vehicle_no,shipping_address,estimated_arrival,actual_arrival,shipping_date,status,freight,return_reason,remark,created_at) VALUES ($1,$2,$3,\\'中通速递\\',\\'司机\\',\\'13800003333\\',\\'粤B88888\\',\\'佛山市禅城区\\',CURRENT_DATE-7,NULL,CURRENT_TIMESTAMP-INTERVAL\\'10 days\\',\\'returned\\',300,\\'超时未妥投自动退回\\',\\'边界测试-超时退回\\',NOW())',")
lines.append("                [rtsId, orders[0].id, 'LF' + ts().slice(-6) + 'RTS']")
lines.append("            );")
lines.append("            console.log('OK 边界物流: 超期退回（已运输10天）');")
lines.append("        }")
lines.append("        if (orders.length > 1) {")
lines.append("            var lateId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO logistics_record (id,order_id,logistics_no,carrier,driver_name,driver_phone,vehicle_no,shipping_address,estimated_arrival,actual_arrival,shipping_date,status,freight,remark,created_at) VALUES ($1,$2,$3,\\'韵达快递\\',\\'司机\\',\\'13800004444\\',\\'粤B77777\\',\\'广州市天河区\\',CURRENT_DATE-3,NULL,CURRENT_TIMESTAMP-INTERVAL\\'5 days\\',\\'in_transit\\',300,\\'边界测试-已超期3天仍未到达\\',NOW())',")
lines.append("                [lateId, orders[1].id, 'LF' + ts().slice(-6) + 'LATE']")
lines.append("            );")
lines.append("            console.log('OK 边界物流: 超期未到达（已超期3天）');")
lines.append("        }")
lines.append("        await client.query('COMMIT');")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createInstallation(orders) {")
lines.append("    console.log('\\n========== 12. 安装任务（正常+异常） ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        var instCities = ['深圳市南山区', '东莞市南城区'];")
lines.append("        for (var ii = 0; ii < Math.min(2, orders.length); ii++) {")
lines.append("            var instId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO installation_task (id,order_id,task_no,installation_type,scheduled_date,scheduled_end_date,actual_start_date,actual_end_date,installation_address,contact_name,contact_phone,status,priority,quality_check,quality_score,quality_remark,customer_satisfaction,remark,operator,created_at) VALUES ($1,$2,$3,\\'新装\\',CURRENT_DATE+1,CURRENT_DATE+3,NULL,NULL,$4,\\'客户\\',\\'13800000001\\',\\'in_progress\\',\\'normal\\',NULL,NULL,NULL,NULL,NULL,NULL,\\'王二\\',NOW())',")
lines.append("                [instId, orders[ii].id, 'IN' + ts().slice(-6) + String(ii), instCities[ii]]")
lines.append("            );")
lines.append("            await client.query(")
lines.append("                'INSERT INTO installer_allocation (id,task_id,employee_id,role,scheduled_hours,actual_hours,overtime_hours,work_date,status,remark,created_at) VALUES ($1,$2,$3,\\'组长\\',8,NULL,0,CURRENT_DATE,\\'assigned\\',\\'正常分配\\',NOW())',")
lines.append("                [uuid(), instId, '王二']")
lines.append("            );")
lines.append("            await client.query(")
lines.append("                'INSERT INTO installer_allocation (id,task_id,employee_id,role,scheduled_hours,actual_hours,overtime_hours,work_date,status,remark,created_at) VALUES ($1,$2,$3,\\'组员\\',8,NULL,0,CURRENT_DATE,\\'assigned\\',\\'正常分配\\',NOW())',")
lines.append("                [uuid(), instId, '郑一']")
lines.append("            );")
lines.append("            console.log('OK 安装: 订单' + ii + ' -> ' + instCities[ii] + ' [进行中]');")
lines.append("        }")
lines.append("        if (orders.length > 2) {")
lines.append("            var failId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO installation_task (id,order_id,task_no,installation_type,scheduled_date,scheduled_end_date,actual_start_date,actual_end_date,installation_address,contact_name,contact_phone,status,priority,quality_check,quality_score,quality_remark,customer_satisfaction,remark,operator,created_at) VALUES ($1,$2,$3,\\'新装\\',CURRENT_DATE-5,CURRENT_DATE-3,CURRENT_TIMESTAMP-INTERVAL\\'5 days\\',CURRENT_TIMESTAMP-INTERVAL\\'3 days\\',\\'佛山市禅城区\\',\\'客户\\',\\'13800000001\\',\\'rework\\',\\'high\\',\\'failed\\',30,\\'台面缝隙超标，门板划伤，需要返工\\',\\'边界测试-安装不合格需返工\\',2,\\'王二\\',NOW())',")
lines.append("                [failId, orders[2].id, 'IN' + ts().slice(-6) + 'FW']")
lines.append("            );")
lines.append("            await client.query(")
lines.append("                'INSERT INTO installation_progress (id,task_id,stage,status,remark,operator,created_at) VALUES ($1,$2,\\'拆旧\\',\\'completed\\',\\'已完成拆旧\\',\\'王二\\',NOW())',")
lines.append("                [uuid(), failId]")
lines.append("            );")
lines.append("            await client.query(")
lines.append("                'INSERT INTO installation_progress (id,task_id,stage,status,remark,operator,created_at) VALUES ($1,$2,\\'安装\\',\\'failed\\',\\'门板划伤，停工\\',\\'郑一\\',NOW())',")
lines.append("                [uuid(), failId]")
lines.append("            );")
lines.append("            await client.query(")
lines.append("                'INSERT INTO installation_progress (id,task_id,stage,status,remark,operator,created_at) VALUES ($1,$2,\\'台面\\',\\'pending\\',\\'等待返工\\',\\'郑一\\',NOW())',")
lines.append("                [uuid(), failId]")
lines.append("            );")
lines.append("            console.log('OK 边界安装: 安装失败需返工（评分30分）');")
lines.append("        }")
lines.append("        if (orders.length > 3) {")
lines.append("            var cmpId = uuid();")
lines.append("            await client.query(")
lines.append("                'INSERT INTO installation_task (id,order_id,task_no,installation_type,scheduled_date,scheduled_end_date,actual_start_date,actual_end_date,installation_address,contact_name,contact_phone,status,priority,quality_check,quality_score,quality_remark,customer_satisfaction,remark,operator,created_at) VALUES ($1,$2,$3,\\'新装\\',CURRENT_DATE-10,CURRENT_DATE-8,CURRENT_TIMESTAMP-INTERVAL\\'10 days\\',CURRENT_TIMESTAMP-INTERVAL\\'8 days\\',\\'惠州市惠城区\\',\\'客户\\',\\'13800000001\\',\\'completed\\',\\'normal\\',\\'passed\\',20,\\'勉强通过\\',\\'很不满意/10\\',\\'边界测试-客户投诉，差评\\',1,\\'王二\\',NOW())',")
lines.append("                [cmpId, orders[3].id, 'IN' + ts().slice(-6) + 'CM']")
lines.append("            );")
lines.append("            console.log('OK 边界安装: 完成但客户差评（满意度20分）');")
lines.append("        }")
lines.append("        await client.query('COMMIT');")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createAttendance(empIds) {")
lines.append("    console.log('\\n========== 13. 考勤（正常+异常） ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        for (var ai = 0; ai < empIds.length; ai++) {")
lines.append("            var emp = empIds[ai];")
lines.append("            // Normal days")
lines.append("            for (var ad = 0; ad < 20; ad++) {")
lines.append("                var d = new Date();")
lines.append("                d.setDate(d.getDate() - ad);")
lines.append("                var dateStr = d.toISOString().split('T')[0];")
lines.append("                await client.query(")
lines.append("                    'INSERT INTO attendance_record (id,employee_id,work_date,status,check_in_time,check_out_time,regular_hours,overtime_hours,leave_type,leave_days,remark,operator,created_at) VALUES ($1,$2,$3,\\'normal\\',$4,$5,8,0,NULL,0,\\'正常\\',$6,NOW())',")
lines.append("                    [uuid(), emp.id, dateStr, '08:0' + String(ad % 10), '18:0' + String(ad % 10), emp.name]")
lines.append("                );")
lines.append("            }")
lines.append("            // Absent (3 days)")
lines.append("            for (var aa = 21; aa <= 23; aa++) {")
lines.append("                var da = new Date();")
lines.append("                da.setDate(da.getDate() - aa);")
lines.append("                var dateStrA = da.toISOString().split('T')[0];")
lines.append("                await client.query(")
lines.append("                    'INSERT INTO attendance_record (id,employee_id,work_date,status,check_in_time,check_out_time,regular_hours,overtime_hours,leave_type,leave_days,remark,operator,created_at) VALUES ($1,$2,$3,\\'absent\\',NULL,NULL,0,0,NULL,0,\\'边界测试-旷工\\',$4,NOW())',")
lines.append("                    [uuid(), emp.id, dateStrA, emp.name]")
lines.append("                );")
lines.append("            }")
lines.append("            // Overtime (6 hours)")
lines.append("            var otDate = new Date();")
lines.append("            otDate.setDate(otDate.getDate() - 24);")
lines.append("            var otDateStr = otDate.toISOString().split('T')[0];")
lines.append("            await client.query(")
lines.append("                'INSERT INTO attendance_record (id,employee_id,work_date,status,check_in_time,check_out_time,regular_hours,overtime_hours,leave_type,leave_days,remark,operator,created_at) VALUES ($1,$2,$3,\\'normal\\',\\'08:00\\',\\'22:30\\',8,6,NULL,0,\\'边界测试-日加班6小时\\',$4,NOW())',")
lines.append("                [uuid(), emp.id, otDateStr, emp.name]")
lines.append("            );")
lines.append("            // Late (5 days)")
lines.append("            for (var al = 25; al <= 29; al++) {")
lines.append("                var dl = new Date();")
lines.append("                dl.setDate(dl.getDate() - al);")
lines.append("                var dateStrL = dl.toISOString().split('T')[0];")
lines.append("                await client.query(")
lines.append("                    'INSERT INTO attendance_record (id,employee_id,work_date,status,check_in_time,check_out_time,regular_hours,overtime_hours,leave_type,leave_days,remark,operator,created_at) VALUES ($1,$2,$3,\\'late\\',\\'09:30\\',\\'18:00\\',7,0,NULL,0,\\'边界测试-迟到\\',$4,NOW())',")
lines.append("                    [uuid(), emp.id, dateStrL, emp.name]")
lines.append("                );")
lines.append("            }")
lines.append("        }")
lines.append("        console.log('OK 考勤: ' + empIds.length + '人 x 30天（含旷工/加班/迟到异常）');")
lines.append("        await client.query('COMMIT');")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createFinance(orders) {")
lines.append("    console.log('\\n========== 14. 财务（正常+异常） ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        for (var fi = 0; fi < Math.min(3, orders.length); fi++) {")
lines.append("            var order = orders[fi];")
lines.append("            var payId = uuid();")
lines.append("            var amount = order.total > 0 ? order.total * 0.3 : rf(1000, 5000);")
lines.append("            await client.query(")
lines.append("                'INSERT INTO payment_in (id,order_id,amount,payment_method,payment_date,bank_reference,payer_name,operator,status,remark,created_at) VALUES ($1,$2,$3,\\'bank_transfer\\',CURRENT_DATE,\\'BNK\\' || $4,\\'客户\\',\\'冯三\\',\\'received\\',\\'正常收款\\',NOW())',")
lines.append("                [payId, order.id, amount, ts().slice(-8)]")
lines.append("            );")
lines.append("            console.log('OK 收款: ¥' + amount.toFixed(2) + ' [正常]');")
lines.append("        }")
lines.append("        // Overdue receivable")
lines.append("        var overId = uuid();")
lines.append("        var overOrder = null;")
lines.append("        for (var oi2 = 0; oi2 < orders.length; oi2++) { if (orders[oi2].total > 0) { overOrder = orders[oi2]; break; } }")
lines.append("        if (!over