#!/usr/bin/env python3
"""Generate full_test_abnormal_v1.js - Part 1 (lines 1-300)"""

path = r'C:\Users\Administrator\Desktop\橱柜工厂管理系统\src\backend\full_test_abnormal_v1.js'

lines = []
lines.append("// ============================================================================")
lines.append("// 橱柜工厂管理系统 - 异常与边界测试 V1")
lines.append("// ============================================================================")
lines.append("const { Pool } = require('pg');")
lines.append("")
lines.append("const pool = new Pool({")
lines.append("    host: process.env.DB_HOST || '10.60.209.202',")
lines.append("    port: parseInt(process.env.DB_PORT || '5432'),")
lines.append("    user: process.env.DB_USER || 'postgres',")
lines.append("    password: process.env.DB_PASS || '87030785',")
lines.append("    database: process.env.DB_NAME || 'cabinet_factory',")
lines.append("    max: 10,")
lines.append("    idleTimeoutMillis: 30000,")
lines.append("});")
lines.append("")
lines.append("const db = { query: function(text, params) { return pool.query(text, params); } };")
lines.append("const uuid = function() { return require('crypto').randomUUID(); };")
lines.append("var ri = function(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; };")
lines.append("var rf = function(min, max) { return parseFloat((Math.random() * (max - min) + min).toFixed(2)); };")
lines.append("var pick = function(arr) { return arr[ri(0, arr.length - 1)]; };")
lines.append("var ts = function() { return Date.now().toString(); };")
lines.append("")
lines.append("async function clearAll() {")
lines.append("    console.log('\\n========================================');")
lines.append("    console.log('  橱柜工厂 - 异常与边界测试 V1');")
lines.append("    console.log('========================================');")
lines.append("    console.log('\\n========== 1. 清空所有数据 ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        var tables = [")
lines.append("            'payment_in', 'receivable',")
lines.append("            'attendance_record',")
lines.append("            'installation_progress', 'installer_allocation', 'installation_task',")
lines.append("            'logistics_track', 'logistics_record',")
lines.append("            'package_item', 'package_record',")
lines.append("            'door_panel_production', 'countertop_production', 'production_schedule',")
lines.append("            'production_worker', 'production_stage',")
lines.append("            'stock_in', 'stock_out', 'stock_inventory',")
lines.append("            'order_tracking', 'order_bom', 'order_detail', 'order_master',")
lines.append("            'material_bom', 'material', 'warehouse', 'supplier',")
lines.append("            'customer', 'employee', 'department',")
lines.append("        ];")
lines.append("        for (var ti = 0; ti < tables.length; ti++) {")
lines.append("            await client.query('DELETE FROM ' + tables[ti]);")
lines.append("        }")
lines.append("        console.log('OK: 清空完成');")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("        await pool.end();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createBasic() {")
lines.append("    console.log('\\n========== 2. 基础数据（部门+员工） ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        var depts = [")
lines.append("            { n: '销售部A', code: 'DEPT-SA' },")
lines.append("            { n: '设计部A', code: 'DEPT-DE' },")
lines.append("            { n: '生产部A', code: 'DEPT-PR' },")
lines.append("            { n: '仓储部A', code: 'DEPT-WH' },")
lines.append("            { n: '物流部A', code: 'DEPT-LO' },")
lines.append("            { n: '安装部A', code: 'DEPT-IN' },")
lines.append("            { n: '财务部A', code: 'DEPT-FI' },")
lines.append("            { n: '人事部A', code: 'DEPT-HR' },")
lines.append("        ];")
lines.append("        var deptIds = {};")
lines.append("        for (var di = 0; di < depts.length; di++) {")
lines.append("            var did = uuid();")
lines.append("            deptIds[depts[di].code] = did;")
lines.append("            await client.query(")
lines.append("                'INSERT INTO department (id,dept_no,dept_name,dept_type,manager_id,status,created_at) VALUES ($1,$2,$3,\\'normal\\',NULL,\\'active\\',NOW())',")
lines.append("                [did, depts[di].code, depts[di].n]")
lines.append("            );")
lines.append("        }")
lines.append("        var emps = [")
lines.append("            { n: '张三', dept: 'DEPT-SA' },")
lines.append("            { n: '李四', dept: 'DEPT-SA' },")
lines.append("            { n: '王五', dept: 'DEPT-DE' },")
lines.append("            { n: '赵六', dept: 'DEPT-DE' },")
lines.append("            { n: '钱七', dept: 'DEPT-PR' },")
lines.append("            { n: '孙八', dept: 'DEPT-PR' },")
lines.append("            { n: '周九', dept: 'DEPT-WH' },")
lines.append("            { n: '吴十', dept: 'DEPT-LO' },")
lines.append("            { n: '郑一', dept: 'DEPT-IN' },")
lines.append("            { n: '王二', dept: 'DEPT-IN' },")
lines.append("            { n: '冯三', dept: 'DEPT-FI' },")
lines.append("            { n: '陈四', dept: 'DEPT-HR' },")
lines.append("        ];")
lines.append("        var empIds = [];")
lines.append("        for (var ei = 0; ei < emps.length; ei++) {")
lines.append("            var eid = uuid();")
lines.append("            empIds.push({ id: eid, name: emps[ei].n, dept: emps[ei].dept });")
lines.append("            await client.query(")
lines.append("                'INSERT INTO employee (id,emp_no,emp_name,dept_id,position,phone,id_card,bank_account,emergency_contact,emergency_phone,status,join_date,created_at) VALUES ($1,$2,$3,$4,\\'员工\\',\\'13800000000\\',\\'440000199001010000\\',\\'622200001\\',\\'紧急联系人\\',\\'13800000001\\',\\'active\\',DATE\\'2024-01-01\\',NOW())',")
lines.append("                [eid, 'E' + ts().slice(-6) + String(ri(100,999)), emps[ei].n, deptIds[emps[ei].dept]]")
lines.append("            );")
lines.append("        }")
lines.append("        await client.query('COMMIT');")
lines.append("        console.log('OK: 部门' + depts.length + '个, 员工' + emps.length + '人');")
lines.append("        return { deptIds: deptIds, empIds: empIds };")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createCustomers() {")
lines.append("    console.log('\\n========== 3. 客户（正常+异常） ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        var custs = [")
lines.append("            { n: '张先生', p: '13800138001', a: '广州市天河区', type: 'normal' },")
lines.append("            { n: '李女士', p: '13800138002', a: '深圳市南山区', type: 'normal' },")
lines.append("            { n: '王先生', p: '138001380000123', a: '佛山市禅城区', type: 'abnormal_phone' },")
lines.append("            { n: '赵先生', p: '13800138004', a: '广州市天河区珠江新城花城大道123号某某小区A栋1501房很长很长的补充描述用于测试字段上限', type: 'abnormal_address' },")
lines.append("            { n: '刘女士', p: '', a: '东莞市南城区', type: 'abnormal_empty' },")
lines.append("            { n: '陈退', p: '13800138006', a: '珠海市香洲区', type: 'abnormal_special' },")
lines.append("        ];")
lines.append("        var custIds = [];")
lines.append("        for (var ci = 0; ci < custs.length; ci++) {")
lines.append("            var cid = uuid();")
lines.append("            custIds.push({ id: cid, name: custs[ci].n, type: custs[ci].type });")
lines.append("            try {")
lines.append("                await client.query(")
lines.append("                    'INSERT INTO customer (id,customer_no,customer_name,phone,address,status,source,created_at) VALUES ($1,$2,$3,$4,$5,\\'following\\',\\'测试\\',NOW())',")
lines.append("                    [cid, 'C' + ts().slice(-6) + String(ri(100,999)), custs[ci].n, custs[ci].p || null, custs[ci].a]")
lines.append("                );")
lines.append("                console.log('OK 客户: ' + custs[ci].n + ' [' + custs[ci].type + ']');")
lines.append("            } catch(err) {")
lines.append("                console.log('FAIL 客户: ' + custs[ci].n + ' [' + custs[ci].type + '] - ' + err.message.split('\\n')[0]);")
lines.append("            }")
lines.append("        }")
lines.append("        await client.query('COMMIT');")
lines.append("        return custIds;")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createSuppliers() {")
lines.append("    console.log('\\n========== 4. 供应商 ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        var sups = [")
lines.append("            { n: '宝钢不锈钢A', code: 'SUP-SS-001' + ts().slice(-4), cat: '不锈钢板' },")
lines.append("            { n: '海德威配件A', code: 'SUP-HW-001' + ts().slice(-4), cat: '五金配件' },")
lines.append("            { n: '华润板材A', code: 'SUP-MB-001' + ts().slice(-4), cat: '基础板材' },")
lines.append("        ];")
lines.append("        var supIds = [];")
lines.append("        for (var si = 0; si < sups.length; si++) {")
lines.append("            var sid = uuid();")
lines.append("            supIds.push({ id: sid, name: sups[si].n });")
lines.append("            await client.query(")
lines.append("                'INSERT INTO supplier (id,supplier_no,supplier_name,contact_name,contact_phone,address,category,status,created_at) VALUES ($1,$2,$3,\\'联系人\\',\\'13800000000\\',\\'广东省佛山市\\',$4,\\'active\\',NOW())',")
lines.append("                [sid, sups[si].code, sups[si].n, sups[si].cat]")
lines.append("            );")
lines.append("            console.log('OK 供应商: ' + sups[si].n);")
lines.append("        }")
lines.append("        await client.query('COMMIT');")
lines.append("        return supIds;")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createWarehouses() {")
lines.append("    console.log('\\n========== 5. 仓库 ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        var t4 = ts().slice(-4);")
lines.append("        var ws = [")
lines.append("            { n: '广州总仓A', code: 'WH001A' + t4 },")
lines.append("            { n: '佛山分仓A', code: 'WH002A' + t4 },")
lines.append("            { n: '深圳分仓A', code: 'WH003A' + t4 },")
lines.append("        ];")
lines.append("        var whIds = [];")
lines.append("        for (var wi = 0; wi < ws.length; wi++) {")
lines.append("            var wid = uuid();")
lines.append("            whIds.push({ id: wid, name: ws[wi].n });")
lines.append("            await client.query(")
lines.append("                'INSERT INTO warehouse (id,warehouse_code,warehouse_name,warehouse_type,province,city,district,address,status,created_at) VALUES ($1,$2,$3,\\'main\\',\\'广东省\\',\\'广州市\\',\\'白云区\\',\\'广州市白云区钟落潭\\',\\'active\\',NOW())',")
lines.append("                [wid, ws[wi].code, ws[wi].n]")
lines.append("            );")
lines.append("            console.log('OK 仓库: ' + ws[wi].n + ' [' + ws[wi].code + ']');")
lines.append("        }")
lines.append("        await client.query('COMMIT');")
lines.append("        return whIds;")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createMaterials() {")
lines.append("    console.log('\\n========== 6. 材料（正常+边界） ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        var t4 = ts().slice(-4);")
lines.append("        var mats = [")
lines.append("            { code: 'MAT-SS-001' + t4, n: '不锈钢板304 1.5mm', cat: '不锈钢板', spec: '1.5mm*1220*2440', u: '张', price: 380 },")
lines.append("            { code: 'MAT-SS-002' + t4, n: '不锈钢板304 2.0mm', cat: '不锈钢板', spec: '2.0mm*1220*2440', u: '张', price: 520 },")
lines.append("            { code: 'MAT-HW-001' + t4, n: '不锈钢铰链', cat: '五金', spec: '304#', u: '个', price: 12 },")
lines.append("            { code: 'MAT-FR-001' + t4, n: '填充材料（价格为零）', cat: '辅助', spec: '免费样料', u: '个', price: 0 },")
lines.append("            { code: 'MAT-LG-001' + t4, n: '超长名称材料用于测试数据库VARCHAR字段上限这个名称非常长需要超过255字符的测试内容来验证前端和后端的截断处理是否正确以及数据库约束是否有效执行' + ts(), cat: '测试', spec: '长名称测试', u: '米', price: 100 },")
lines.append("        ];")
lines.append("        var matIds = [];")
lines.append("        for (var mi = 0; mi < mats.length; mi++) {")
lines.append("            var mid = uuid();")
lines.append("            matIds.push({ id: mid, name: mats[mi].n, price: mats[mi].price });")
lines.append("            try {")
lines.append("                await client.query(")
lines.append("                    'INSERT INTO material (id,material_code,material_name,category,spec,unit,unit_price,status,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,\\'active\\',NOW())',")
lines.append("                    [mid, mats[mi].code, mats[mi].n, mats[mi].cat, mats[mi].spec, mats[mi].u, mats[mi].price]")
lines.append("                );")
lines.append("                console.log('OK 材料: ' + mats[mi].n.substring(0,30) + '... [¥' + mats[mi].price + ']');")
lines.append("            } catch(err) {")
lines.append("                console.log('FAIL 材料: ' + mats[mi].n.substring(0,30) + '... - ' + err.message.split('\\n')[0]);")
lines.append("            }")
lines.append("        }")
lines.append("        await client.query('COMMIT');")
lines.append("        return matIds;")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("async function createOrders(custIds) {")
lines.append("    console.log('\\n========== 7. 订单（正常+边界） ==========');")
lines.append("    var client = await pool.connect();")
lines.append("    try {")
lines.append("        await client.query('BEGIN');")
lines.append("        var orders = [];")
lines.append("        for (var oi = 0; oi < 3; oi++) {")
lines.append("            var oid = uuid();")
lines.append("            var custId = custIds[oi % custIds.length].id;")
lines.append("            var total = rf(5000, 50000);")
lines.append("            await client.query(")
lines.append("                'INSERT INTO order_master (id,order_no,customer_id,order_date,delivery_date,total_amount,paid_amount,order_status,production_status,installation_status,design_status,quality_status,logistics_status,invoice_status,source,priority,assigned_to,estimator,estimator_hours,designer,design_hours,warehouse_id,shipping_address,contact_phone,contact_name,remark,created_at) VALUES ($1,$2,$3,CURRENT_DATE,CURRENT_DATE+15,$4,0,\\'pending\\',\\'not_started\\',\\'not_started\\',\\'not_started\\',\\'not_started\\',\\'not_started\\',\\'not_started\\',\\'store\\',\\'normal\\',NULL,NULL,0,NULL,0,NULL,$5,\\'13800138000\\',\\'客户\\',\\'正常订单测试\\',NOW())',")
lines.append("                [oid, 'O' + ts() + String(ri(100,999)), custId, total, '广州市天河区']")
lines.append("            );")
lines.append("            await client.query(")
lines.append("                'INSERT INTO order_detail (id,order_id,product_name,product_type,length,width,height,quantity,unit_price,discount,total_price,door_panel_count,countertop_count,status,created_at) VALUES ($1,$2,\\'不锈钢橱柜\\',\\'标准型\\',800,600,800,2,$3,0,$3*2,\\'pending\\',NOW())',")
lines.append("                [uuid(), oid, total / 2]")
lines.append("            );")
lines.append("            orders.push({ id: oid, total: total });")
lines.append("            console.log('OK 订单: ' + oid.substring(0,8) + '... ¥' + total.toFixed(2));")
lines.append("        }")
lines.append("        // Zero amount")
lines.append("        var id0 = uuid();")
lines.append("        try {")
lines.append("            await client.query(")
lines.append("                'INSERT INTO order_master (id,order_no,customer_id,order_date,delivery_date,total_amount,paid_amount,order_status,production_status,installation_status,design_status,quality_status,logistics_status,invoice_status,source,priority,assigned_to,shipping_address,contact_phone,contact_name,remark,created_at) VALUES ($1,$2,$3,CURRENT_DATE,CURRENT_DATE+15,0,0,\\'pending\\',\\'not_started\\',\\'not_started\\',\\'not_started\\',\\'not_started\\',\\'not_started\\',\\'not_started\\',\\'store\\',\\'normal\\',NULL,\\'地址\\',\\'13800000000\\',\\'客户\\',\\'边界测试-零金额订单\\',NOW())',")
lines.append("                [id0, 'O' + ts() + 'ZERO', custIds[0].id]")
lines.append("            );")
lines.append("            orders.push({ id: id0, total: 0 });")
lines.append("            console.log('OK 边界订单: 零金额');")
lines.append("        } catch(err) {")
lines.append("            console.log('FAIL 边界订单: 零金额 - ' + err.message.split('\\n')[0]);")
lines.append("        }")
lines.append("        // Overdue delivery")
lines.append("        var id1 = uuid();")
lines.append("        await client.query(")
lines.append("            'INSERT INTO order_master (id,order_no,customer_id,order_date,delivery_date,total_amount,paid_amount,order_status,production_status,installation_status,design_status,quality_status,logistics_status,invoice_status,source,priority,assigned_to,shipping_address,contact_phone,contact_name,remark,created_at) VALUES ($1,$2,$3,DATE\\'2026-03-01\\',DATE\\'2026-03-15\\',$4,0,\\'processing\\',\\'in_production\\',\\'not_started\\',\\'completed\\',\\'pending\\',\\'in_transit\\',\\'not_started\\',\\'store\\',\\'high\\',NULL,\\'地址\\',\\'13800000000\\',\\'客户\\',\\'边界测试-逾期订单（已逾期6天）\\',NOW())',")
lines.append("            [id1, 'O' + ts() + 'LATE', custIds[1 % custIds.length].id, rf(10000, 30000)]")
lines.append("        );")
lines.append("        await client.query(")
lines.append("            'INSERT INTO order_detail (id,order_id,product_name,product_type,length,width,height,quantity,unit_price,discount,total_price,door_panel_count,countertop_count,status,created_at) VALUES ($1,$2,\\'不锈钢橱柜\\',\\'标准型\\',800,600,800,3,$3,0,$3*3,\\'in_production\\',NOW())',")
lines.append("            [uuid(), id1, rf(3000, 8000)]")
lines.append("        );")
lines.append("        orders.push({ id: id1, total: 0, late: true });")
lines.append("        console.log('OK 边界订单: 逾期交货（delivery_date已过）');")
lines.append("        // Overpaid")
lines.append("        var id2 = uuid();")
lines.append("        var total3 = rf(5000, 10000);")
lines.append("        var overpaid = total3 * 1.5;")
lines.append("        await client.query(")
lines.append("            'INSERT INTO order_master (id,order_no,customer_id,order_date,delivery_date,total_amount,paid_amount,order_status,production_status,installation_status,design_status,quality_status,logistics_status,invoice_status,source,priority,assigned_to,shipping_address,contact_phone,contact_name,remark,created_at) VALUES ($1,$2,$3,CURRENT_DATE,CURRENT_DATE+15,$4,$5,\\'processing\\',\\'in_production\\',\\'not_started\\',\\'completed\\',\\'pending\\',\\'pending\\',\\'not_started\\',\\'store\\',\\'normal\\',NULL,\\'地址\\',\\'13800000000\\',\\'客户\\',\\'边界测试-超额付款\\',NOW())',")
lines.append("            [id2, 'O' + ts() + 'OVER', custIds[2 % custIds.length].id, total3, overpaid]")
lines.append("        );")
lines.append("        orders.push({ id: id2, total: total3, paid: overpaid });")
lines.append("        console.log('OK 边界订单: 超额付款 ¥' + total3.toFixed(2) + ' 已付 ¥' + overpaid.toFixed(2));")
lines.append("        // Urgent")
lines.append("        var id4 = uuid();")
lines.append("        await client.query(")
lines.append("            'INSERT INTO order_master (id,order_no,customer_id,order_date,delivery_date,total_amount,paid_amount,order_status,production_status,installation_status,design_status,quality_status,logistics_status,invoice_status,source,priority,assigned_to,shipping_address,contact_phone,contact_name,remark,created_at) VALUES ($1,$2,$3,CURRENT_DATE,CURRENT_DATE+3,$4,0,\\'processing\\',\\'in_production\\',\\'not_started\\',\\'completed\\',\\'pending\\',\\'pending\\',\\'not_started\\',\\'store\\',\\'urgent\\',NULL,\\'紧急地址\\',\\'13800000000\\',\\'客户\\',\\'边界测试-紧急订单（3天后交付）\\',NOW())',")
lines.append("            [id4, 'O' + ts() + 'URGT', custIds[0].id, rf(20000, 80000)]")
lines.append("        );")
lines.append("        orders.push({ id: id4, total: 0, urgent: true });")
lines.append("        console.log('OK 边界订单: 紧急订单（3天交付）');")
lines.append("        await client.query('COMMIT');")
lines.append("        return orders;")
lines.append("    } catch(err) {")
lines.append("        await client.query('ROLLBACK');")
lines.append("        throw err;")
lines.append("    } finally {")
lines.append("        client.release();")
lines.append("    }")
lines.append("}")

with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print('Part 1 written: ' + str(len(lines)) + ' lines')
